global using Autofac;
global using Autofac.Extras.Moq;
global using Domain.Entities;
global using Domain.Common.Errors;
global using ErrorOr;
global using Mapster;
global using MapsterMapper;
global using Moq;
global using Xunit;